# Generated by Django 5.1.4 on 2025-03-30 15:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('batchid', models.PositiveIntegerField(db_column='batchId', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(7)])),
                ('coursename', models.CharField(blank=True, db_column='courseName', max_length=15, null=True)),
                ('joinyear', models.IntegerField(blank=True, db_column='joinYear', null=True, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(7)])),
                ('endyear', models.IntegerField(blank=True, db_column='endYear', null=True, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(7)])),
            ],
            options={
                'db_table': 'batches',
            },
        ),
        migrations.CreateModel(
            name='EventCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('image_url', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_categories',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=15, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('profile_url', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=20)),
                ('start_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(4)])),
                ('end_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(4)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='OfficialAlumni',
            fields=[
                ('regno', models.PositiveIntegerField(db_column='regNo', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(4)])),
                ('studentname', models.CharField(db_column='studentName', max_length=40)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('instmail', models.EmailField(blank=True, db_column='instMail', max_length=23, null=True)),
                ('personalmail', models.EmailField(blank=True, db_column='personalMail', max_length=255, null=True)),
                ('is_registered', models.BooleanField(default=False)),
                ('batchid', models.ForeignKey(db_column='batchId', on_delete=django.db.models.deletion.PROTECT, to='core.batches')),
            ],
            options={
                'db_table': 'official_alumni',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(15)])),
                ('course_name', models.CharField(max_length=15)),
                ('batch_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.batches')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.users')),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='NewsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('image_url', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_newscategories', to='core.users')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_newscategories', to='core.users')),
            ],
            options={
                'db_table': 'news_categories',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('news_date', models.DateField()),
                ('news_slug', models.SlugField(max_length=20, unique=True)),
                ('image_url', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('news_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.newscategories')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_news', to='core.users')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_news', to='core.users')),
            ],
            options={
                'db_table': 'news',
                'ordering': ['-news_date'],
            },
        ),
        migrations.CreateModel(
            name='faculties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(max_length=15)),
                ('designation', models.CharField(max_length=25)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.users')),
            ],
            options={
                'db_table': 'faculties',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('event_time', models.TimeField()),
                ('event_date', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=254)),
                ('event_slug', models.SlugField(max_length=20, unique=True)),
                ('image_url', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.eventcategories')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_events', to='core.users')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_events', to='core.users')),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-event_date'],
            },
        ),
        migrations.AddField(
            model_name='eventcategories',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_eventcategories', to='core.users'),
        ),
        migrations.AddField(
            model_name='eventcategories',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_eventcategories', to='core.users'),
        ),
        migrations.CreateModel(
            name='alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumni_id', models.CharField(max_length=15)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.users')),
            ],
            options={
                'db_table': 'alumni',
            },
        ),
    ]
