# Generated by Django 5.1.4 on 2025-04-08 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('guidance_areas', models.CharField(max_length=250)),
                ('contact_method', models.CharField(max_length=250)),
                ('availability', models.CharField(max_length=250)),
                ('linkedin', models.CharField(max_length=250)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to='core.users')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='core.users')),
            ],
            options={
                'db_table': 'mentor',
            },
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_note', models.CharField(max_length=250)),
                ('status', models.BooleanField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_at', to='core.users')),
                ('mentee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_id', to='core.users')),
                ('mentor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_id', to='core.mentor')),
            ],
            options={
                'db_table': 'mentee',
            },
        ),
    ]
