# Generated by Django 5.1.4 on 2025-04-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mentor_mentee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='approved_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
