# Generated by Django 5.1.4 on 2025-04-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_mentee_approved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
