# Generated by Django 5.1.4 on 2025-04-28 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_nonmonetarycontribution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NonMonetaryContribution',
        ),
    ]
