# Generated by Django 5.1.4 on 2025-04-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_nonmonetarycontribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonMonetaryContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('session_date', models.DateField()),
                ('session_time', models.TimeField()),
                ('session_topic', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'contributions',
            },
        ),
    ]
