# Generated by Django 5.1.4 on 2025-04-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_nonmonetarycontribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterOfRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('alumni', 'Alumni'), ('staff', 'Staff')], max_length=10)),
                ('template', models.CharField(choices=[('academic', 'Academic'), ('job', 'Job'), ('general', 'General')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('recommender_name', models.CharField(max_length=255)),
                ('recommender_title', models.CharField(max_length=255)),
                ('academic_performance', models.TextField(blank=True, null=True)),
                ('work_experience', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('projects', models.TextField(blank=True, null=True)),
                ('areas_of_contribution', models.TextField(blank=True, null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lor',
            },
        ),
    ]
