# Generated by Django 5.1.4 on 2025-04-28 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_letterofrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterofrecommendation',
            name='user_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letters_of_recommendation', to='core.users'),
        ),
    ]
